/*----------------------------------------------------------------------------
Exports
----------------------------------------------------------------------------*/
export const formationsOptions = [
  {
    formation: '3 - 2 - 2 - 3',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 75,
        y: 75,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 50,
        y: 75,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 25,
        y: 75,
      },
      {
        i: 'player-5',
        position: 'Midfielder',
        x: 35,
        y: 55,
      },
      {
        i: 'player-6',
        position: 'Midfielder',
        x: 65,
        y: 55,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 75,
        y: 40,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 25,
        y: 40,
      },
      {
        i: 'player-9',
        position: 'Attacker',
        x: 90,
        y: 20,
      },
      {
        i: 'player-10',
        position: 'Attacker',
        x: 10,
        y: 20,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 50,
        y: 10,
      },
    ],
  },
  {
    formation: '3 - 4 - 3',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 75,
        y: 75,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 50,
        y: 75,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 25,
        y: 75,
      },
      {
        i: 'player-5',
        position: 'Midfielder',
        x: 35,
        y: 55,
      },
      {
        i: 'player-6',
        position: 'Midfielder',
        x: 65,
        y: 55,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 85,
        y: 40,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 15,
        y: 40,
      },
      {
        i: 'player-9',
        position: 'Attacker',
        x: 90,
        y: 20,
      },
      {
        i: 'player-10',
        position: 'Attacker',
        x: 10,
        y: 20,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 50,
        y: 10,
      },
    ],
  },
  {
    formation: '3 - 5 - 2',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 75,
        y: 75,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 50,
        y: 75,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 25,
        y: 75,
      },
      {
        i: 'player-5',
        position: 'Midfielder',
        x: 35,
        y: 60,
      },
      {
        i: 'player-6',
        position: 'Midfielder',
        x: 65,
        y: 60,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 85,
        y: 40,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 50,
        y: 40,
      },
      {
        i: 'player-9',
        position: 'Attacker',
        x: 15,
        y: 40,
      },
      {
        i: 'player-10',
        position: 'Attacker',
        x: 65,
        y: 10,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 35,
        y: 10,
      },
    ],
  },
  {
    formation: '4 - 2 - 3 - 1',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 85,
        y: 70,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 65,
        y: 80,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 35,
        y: 80,
      },
      {
        i: 'player-5',
        position: 'Defender',
        x: 15,
        y: 70,
      },
      {
        i: 'player-6',
        position: 'Midfielder',
        x: 65,
        y: 55,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 35,
        y: 55,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 85,
        y: 35,
      },
      {
        i: 'player-9',
        position: 'Midfielder',
        x: 50,
        y: 35,
      },
      {
        i: 'player-10',
        position: 'Midfielder',
        x: 15,
        y: 35,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 50,
        y: 10,
      },
    ],
  },
  {
    formation: '4 - 3 - 3',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 85,
        y: 70,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 65,
        y: 80,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 35,
        y: 80,
      },
      {
        i: 'player-5',
        position: 'Defender',
        x: 15,
        y: 70,
      },
      {
        i: 'player-6',
        position: 'Midfielder',
        x: 50,
        y: 60,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 65,
        y: 45,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 35,
        y: 45,
      },
      {
        i: 'player-9',
        position: 'Attacker',
        x: 85,
        y: 20,
      },
      {
        i: 'player-10',
        position: 'Attacker',
        x: 15,
        y: 20,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 50,
        y: 10,
      },
    ],
  },
  {
    formation: '4 - 4 - 2',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 85,
        y: 70,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 65,
        y: 80,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 35,
        y: 80,
      },
      {
        i: 'player-5',
        position: 'Defender',
        x: 15,
        y: 70,
      },
      {
        i: 'player-6',
        position: 'Midfielder',
        x: 65,
        y: 55,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 35,
        y: 55,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 85,
        y: 35,
      },
      {
        i: 'player-9',
        position: 'Midfielder',
        x: 15,
        y: 35,
      },
      {
        i: 'player-10',
        position: 'Attacker',
        x: 65,
        y: 10,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 35,
        y: 10,
      },
    ],
  },
  {
    formation: '4 - 5 - 1',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 85,
        y: 70,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 65,
        y: 80,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 35,
        y: 80,
      },
      {
        i: 'player-5',
        position: 'Defender',
        x: 15,
        y: 70,
      },
      {
        i: 'player-6',
        position: 'Midfielder',
        x: 50,
        y: 50,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 65,
        y: 45,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 35,
        y: 45,
      },
      {
        i: 'player-9',
        position: 'Midfielder',
        x: 85,
        y: 30,
      },
      {
        i: 'player-10',
        position: 'Midfielder',
        x: 15,
        y: 30,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 50,
        y: 10,
      },
    ],
  },
  {
    formation: '5 - 4 - 1',
    players: [
      {
        i: 'player-1',
        position: 'Goalkeeper',
        x: 50,
        y: 93,
      },
      {
        i: 'player-2',
        position: 'Defender',
        x: 90,
        y: 65,
      },
      {
        i: 'player-3',
        position: 'Defender',
        x: 70,
        y: 75,
      },
      {
        i: 'player-4',
        position: 'Defender',
        x: 50,
        y: 75,
      },
      {
        i: 'player-5',
        position: 'Defender',
        x: 30,
        y: 75,
      },
      {
        i: 'player-6',
        position: 'Defender',
        x: 10,
        y: 65,
      },
      {
        i: 'player7',
        position: 'Midfielder',
        x: 65,
        y: 50,
      },
      {
        i: 'player-8',
        position: 'Midfielder',
        x: 35,
        y: 50,
      },
      {
        i: 'player-9',
        position: 'Midfielder',
        x: 80,
        y: 30,
      },
      {
        i: 'player-10',
        position: 'Midfielder',
        x: 20,
        y: 30,
      },
      {
        i: 'player-11',
        position: 'Attacker',
        x: 50,
        y: 10,
      },
    ],
  },
];
